### ISSUE TITLE
building native image with graalvm ce 21 not working

### ISSUE THREAD

**Issue by skateball** [SAP-samples/cap-sflight#980]
Hi colleagues,
as already talked to Marc 
 - building the native image with graalvm ce 17 is working fine
 - building the native image with graalvm ce 21 is not working
Best Regards
Chr

**Comment by beckermarc** [comment]
Unfortunately there is a bug in GraalVM 17, that was fixed by Oracle in GraalVM 21 (see https://github.com/oracle/graal/issues/6457). To make it work on 17 we added a [custom native-image.properties](https://github.com/SAP-samples/cap-sflight/blob/main/srv/src/main/resources/META-INF/native-image/native-image.properties) configuration, that has the same effect as the fix automatically applied on GraalVM 21. However on GraalVM 21 this configuration clashes with the provided fix and produces an error.

As SFlight [uses Java 17 by default](https://github.com/SAP-samples/cap-sflight/blob/main/pom.xml#L24), I would like to keep it compatible with GraalVM 17 by default. If you want to run with 21 you need to remove the `native-image.properties` file before building the application (make sure to add `clean` to your Maven build command, if built previously). Then it works with GraalVM 21.
